# Run with:
# launch launch_main.sh --classical_logfile_names --gpu_type rtxa5000 --mem 30

# python main.py --model tomg-group-umd/Qwen3-8B_train_3k_balanced_grpo_ex3000_lr3.0822566060401375e-06_bs64_len1024 --dataset tomg-group-umd/compliance --split train_80k_mix --num_examples 9000 --run_grpo --grpo_lr 3.0822566060401375e-06 --checkpoint_dir /fs/cml-projects/guardian_models/verl
# python main.py --model Qwen/Qwen3-8B --dataset tomg-group-umd/compliance --split train_80k_mix --num_examples 6000 --run_grpo --grpo_lr 1e-6 --checkpoint_dir /fs/cml-projects/guardian_models/verl --resume_grpo
# python main.py --model Qwen/Qwen3-8B-Base --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_lr 1e-6 --grpo_examples 9000 --checkpoint_dir /fs/cml-projects/guardian_models/verl --resume_grpo

# python main.py --model Qwen/Qwen3-8B --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 2e-6 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 64 --grpo_lr 2.6e-6 --grpo_examples 15000 --checkpoint_dir /fs/cml-projects/guardian_models/verl
# python main.py --model Qwen/Qwen3-4B --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 64 --sft_lr 4.8e-6 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 64 --grpo_lr 2.5e-6 --grpo_examples 15000 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model Qwen/Qwen3-1.7B --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 256 --sft_lr 4.8e-6 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 32 --grpo_lr 2e-6 --grpo_examples 15000 --checkpoint_dir /fs/cml-projects/guardian_models/verl --max_prompt_length 4096


# python main.py --model Qwen/Qwen3-8B --dataset tomg-group-umd/compliance --split train_80k_mix --run_grpo --grpo_batch_size 64 --grpo_lr 2.6e-6 --grpo_examples 15000 --checkpoint_dir /fs/cml-projects/guardian_models/verl
# python main.py --model Qwen/Qwen3-1.7B --dataset tomg-group-umd/compliance --split train_80k_mix --run_grpo --grpo_batch_size 32 --grpo_lr 2e-6 --grpo_examples 15000 --checkpoint_dir /fs/cml-projects/guardian_models/verl --max_prompt_length 4096 --resume_grpo

# python main.py --model tomg-group-umd/Qwen3-8B_train_80k_mix_sft_lr1e-5_bs128_ep1_cosine --dataset tomg-group-umd/compliance --split train_80k_mix --run_grpo --grpo_batch_size 48 --num_generations 12 --grpo_lr 1e-6 --grpo_examples 15000 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 10 --save_freq 47 --resume_grpo

# python main.py --model Qwen/Qwen3-1.7B --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model Qwen/Qwen3-1.7B --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 3e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 3e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 2e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 2e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
#  
# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 4e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 4e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47

# python main.py --model meta-llama/Llama-3.2-1B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model meta-llama/Llama-3.2-3B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model meta-llama/Llama-3.2-1B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 3e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 3e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model meta-llama/Llama-3.2-3B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 2e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 2e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model meta-llama/Llama-3.2-1B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 6e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 6e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model meta-llama/Llama-3.2-3B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 4e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 4e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47

# python main.py --model meta-llama/Llama-3.2-1B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 6e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 6e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model meta-llama/Llama-3.2-3B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47 --resume_grpo

# python main.py --model tomg-group-umd/Qwen3-8B_train_80k_mix_grpo_ex9000_lr1e-6_bs48_len1024 --dataset tomg-group-umd/compliance --split train_80k_mix --num_examples 6750 --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_generations 12 --num_checkpoints_to_keep 3 --save_freq 47 --resume_grpo

# python main.py --model mistralai/Ministral-8B-Instruct-2410  --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model mistralai/Ministral-8B-Instruct-2410  --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 3e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 3e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47
# python main.py --model mistralai/Ministral-8B-Instruct-2410  --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 7e-6 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 7e-7 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47

# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_40k_compliance_cot --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 1 --save_freq 47
# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_40k_safety_cot --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 1 --save_freq 47
# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_40k_safety --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --checkpoint_dir /fs/cml-projects/guardian_models/verl
# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_80k_mix --num_examples 40000 --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11255 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 1 --save_freq 47

# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_40k_safety --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --checkpoint_dir /fs/cml-projects/guardian_models/verl
# python main.py --model Qwen/Qwen3-4B   --dataset tomg-group-umd/compliance --split train_40k_compliance --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine  --checkpoint_dir /fs/cml-projects/guardian_models/verl
# python main.py --model yueliu1999/GuardReasoner-8B  --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 1 --save_freq 47 --resume_grpo
# python main.py --model meta-llama/Llama-3.2-1B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 3e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 3e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 1 --save_freq 47 --resume_grpo
# python main.py --model meta-llama/Llama-3.2-3B-Instruct --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 2e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 2e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 1 --save_freq 47 --resume_grpo
# python main.py --model mistralai/Ministral-8B-Instruct-2410  --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 1e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 1e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 1 --save_freq 47

python main.py --model Qwen/Qwen3-1.7B --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 3e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 3e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47 --seed 2

python main.py --model Qwen/Qwen3-1.7B --dataset tomg-group-umd/compliance --split train_80k_mix --run_sft --sft_batch_size 128 --sft_lr 3e-5 --sft_lr_schedule cosine --run_grpo --grpo_batch_size 48 --grpo_lr 3e-6 --grpo_examples 11250 --checkpoint_dir /fs/cml-projects/guardian_models/verl --num_checkpoints_to_keep 3 --save_freq 47 --seed 3