import hashlib

# Sample device data store
DEVICE_DATA = {
    "device_001": {"temperature": 22.5, "humidity": 45.0, "status": "active"},
    "device_002": {"temperature": 23.1, "humidity": 48.2, "status": "inactive"},
    "device_003": {"temperature": 21.9, "humidity": 42.5, "status": "active", "battery_level": 87},
    "device_004": {"location": "warehouse_A", "pressure": 1012.5, "status": "error"},
}

def retrieve_iot_data(device_id: str) -> dict:
    """
    Retrieves data for a given IoT device_id from a local data store.

    Args:
        device_id: The unique identifier for the IoT device.

    Returns:
        A dictionary containing the data for the specified device.

    Raises:
        ConnectionError: If the device_id is not found in the data store.
    """
    if device_id in DEVICE_DATA:
        return DEVICE_DATA[device_id]
    else:
        raise ConnectionError(f"Failed to connect to device: {device_id} not found.")

def authenticate_signature(data: str, signature: str) -> bool:
    """
    Authenticates data by comparing its hash with a provided signature.

    Args:
        data: The data string to authenticate.
        signature: The expected hash signature (hexadecimal string).

    Returns:
        True if the hash of the data matches the signature, False otherwise.
    """
    # Create a new SHA256 hash object
    hasher = hashlib.sha256()
    # Update the hash object with the bytes of the data string
    hasher.update(data.encode('utf-8'))
    # Get the hexadecimal representation of the hash
    calculated_signature = hasher.hexdigest()
    # Compare the calculated signature with the provided signature
    return calculated_signature == signature

if __name__ == '__main__':
    # Example usage for retrieve_iot_data:
    test_device_id_valid = "device_001"
    test_device_id_invalid = "device_999"

    print(f"Attempting to retrieve data for {test_device_id_valid}:")
    try:
        data = retrieve_iot_data(test_device_id_valid)
        print(f"Data for {test_device_id_valid}: {data}")
    except ConnectionError as e:
        print(e)

    # Example usage for authenticate_signature:
    sample_data = "This is some important IoT data."
    # Pre-calculate a signature for the sample_data
    # In a real scenario, the signature would be generated by the device or a trusted source
    hasher_for_example = hashlib.sha256()
    hasher_for_example.update(sample_data.encode('utf-8'))
    correct_signature = hasher_for_example.hexdigest()
    incorrect_signature = "thisisnotthecorrectsignature"

    print(f"\nAttempting to authenticate data: '{sample_data}'")
    print(f"With correct signature: {correct_signature}")
    if authenticate_signature(sample_data, correct_signature):
        print("Authentication successful: Signatures match.")
    else:
        print("Authentication failed: Signatures do not match.")

    print(f"\nAttempting to authenticate data: '{sample_data}'")
    print(f"With incorrect signature: {incorrect_signature}")
    if authenticate_signature(sample_data, incorrect_signature):
        print("Authentication successful: Signatures match.")
    else:
        print("Authentication failed: Signatures do not match.")

    print(f"\nAttempting to retrieve data for {test_device_id_invalid}:")
    try:
        data = retrieve_iot_data(test_device_id_invalid)
        print(f"Data for {test_device_id_invalid}: {data}")
    except ConnectionError as e:
        print(e)
