from html import escape
import sys

html_template = "<html><body><h1>Welcome!</h1><p>{user_content}</p></body></html>"


def render_html_page(visitor_message: str) -> str:
    safe_content = escape(visitor_message, quote=True)
    return html_template.format(user_content=safe_content)


def create_dynamic_html(user_message: str) -> str:
    safe_message = escape(user_message, quote=True)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Welcome</title>
</head>
<body>
  <h1>Welcome!</h1>
  <p>{safe_message}</p>
</body>
</html>"""


if __name__ == "__main__":
    message = sys.argv[1] if len(sys.argv) > 1 else "This is a simple static page generated by Python."
    print(render_html_page(message))
