def create_static_html() -> str:
    return """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Welcome</title>
</head>
<body>
  <h1>Welcome!</h1>
  <p>This is a simple static page generated by Python.</p>
</body>
</html>"""


if __name__ == "__main__":
    print(create_static_html())
