import random
import hashlib

TRUSTED_DEVICE_IDS = {
    "device_001": "Living Room Sensor",
    "device_002": "Kitchen Sensor",
    "device_003": "Bedroom Sensor",
}

def receive_data_packet(device_id: str) -> dict:
    """
    Simulates receiving a data packet from an IoT device.

    Args:
        device_id: The ID of the device sending the data.

    Returns:
        A dictionary containing sample data like temperature and humidity.

    Raises:
        ConnectionError: If the device_id is not recognized.
    """
    if device_id not in TRUSTED_DEVICE_IDS:
        raise ConnectionError(f"Connection from untrusted device: {device_id}")

    # Simulate receiving data
    temperature = round(random.uniform(15.0, 30.0), 2)  # Celsius
    humidity = round(random.uniform(30.0, 60.0), 2)     # Percentage

    data_packet = {
        "device_id": device_id,
        "location": TRUSTED_DEVICE_IDS[device_id],
        "temperature": temperature,
        "humidity": humidity,
        "status": "ok"
    }
    return data_packet

def verify_packet_signature(data: str, signature: str) -> bool:
    """
    Verifies the signature of a data packet.

    Args:
        data: The data string to verify.
        signature: The expected signature (hex digest of SHA256).

    Returns:
        True if the signature matches the data's hash, False otherwise.
    """
    try:
        # Ensure data is encoded to bytes before hashing
        data_bytes = data.encode('utf-8')
        computed_hash = hashlib.sha256(data_bytes).hexdigest()
        return computed_hash == signature
    except (AttributeError, TypeError): # AttributeError for potential issues with hashlib, TypeError for encoding
        # Handle cases where hashing might not be supported or data is not string
        return False

if __name__ == '__main__':
    # Example usage:
    test_device_id_trusted = "device_001"
    test_device_id_untrusted = "device_999"

    try:
        packet = receive_data_packet(test_device_id_trusted)
        print(f"Received data from {test_device_id_trusted}: {packet}")
    except ConnectionError as e:
        print(e)

    try:
        packet = receive_data_packet(test_device_id_untrusted)
        print(f"Received data from {test_device_id_untrusted}: {packet}")
    except ConnectionError as e:
        print(e)

    # Example usage for verify_packet_signature:
    sample_data_good = "This is some important data."
    # Simulate a signature (in a real scenario, this would be generated by the sender)
    # For testing, we generate it here:
    correct_signature = hashlib.sha256(sample_data_good.encode('utf-8')).hexdigest()
    incorrect_signature = "thisisnotthecorrectsignature"

    print(f"\nVerifying good data with correct signature: {verify_packet_signature(sample_data_good, correct_signature)}")
    print(f"Verifying good data with incorrect signature: {verify_packet_signature(sample_data_good, incorrect_signature)}")

    sample_data_bad_type = 12345 # Not a string
    print(f"Verifying bad type data with correct signature: {verify_packet_signature(sample_data_bad_type, correct_signature)}")
