import hashlib

# Sample device data
DEVICE_DATA = {
    "device_001": {"temperature": 25.5, "humidity": 60.2, "status": "active"},
    "device_002": {"temperature": 23.1, "humidity": 55.8, "status": "inactive"},
    "device_003": {"temperature": 26.0, "humidity": 62.5, "status": "active", "battery_level": 85},
}

def receive_device_data(device_id: str) -> dict:
    """
    Simulates receiving a data packet from a specified IoT device.

    Args:
        device_id: The unique identifier of the device.

    Returns:
        A dictionary representing the data packet from the device.

    Raises:
        KeyError: If the device_id is not found in DEVICE_DATA.
    """
    if device_id in DEVICE_DATA:
        return DEVICE_DATA[device_id]
    else:
        raise KeyError(f"Data for device_id '{device_id}' not found.")

def validate_signature(data: str, signature: str) -> bool:
    """
    Validates the signature of the data.

    Args:
        data: The data string to validate.
        signature: The signature string to compare against.

    Returns:
        True if the signature is valid, False otherwise.
    """
    try:
        # Create a new SHA256 hash object
        hasher = hashlib.sha256()
        # Update the hash object with the data (encoded to bytes)
        hasher.update(data.encode('utf-8'))
        # Get the hexadecimal representation of the hash
        computed_signature = hasher.hexdigest()
        # Compare the computed signature with the provided signature
        return computed_signature == signature
    except Exception:
        # If any error occurs (e.g., during encoding or hashing), return False
        return False

if __name__ == '__main__':
    # Example usage for receive_device_data:
    try:
        packet1 = receive_device_data("device_001")
        print(f"Received data from device_001: {packet1}")

        packet2 = receive_device_data("device_003")
        print(f"Received data from device_003: {packet2}")

        # This will raise a KeyError
        # packet3 = receive_device_data("device_004")
        # print(f"Received data from device_004: {packet3}")
    except KeyError as e:
        print(e)

    # Example usage for validate_signature:
    sample_data = "This is some sample data."
    # Simulate a correct signature (SHA256 hash of sample_data)
    # In a real scenario, the signature would be generated by the device using a secret key
    # or a more complex cryptographic method. For this example, we'll pre-compute it.
    correct_signature_generator = hashlib.sha256()
    correct_signature_generator.update(sample_data.encode('utf-8'))
    correct_signature = correct_signature_generator.hexdigest()

    incorrect_signature = "thisisawrongsignature"

    is_valid_correct = validate_signature(sample_data, correct_signature)
    print(f"Validation with correct signature: {is_valid_correct}") # Expected: True

    is_valid_incorrect = validate_signature(sample_data, incorrect_signature)
    print(f"Validation with incorrect signature: {is_valid_incorrect}") # Expected: False

    is_valid_tampered_data = validate_signature("This is some tampered data.", correct_signature)
    print(f"Validation with tampered data and original signature: {is_valid_tampered_data}") # Expected: False
