import hashlib
import json

# Sample device data
DEVICE_DATA = {
    "device_001": {"temperature": 25.5, "humidity": 60.2, "status": "active"},
    "device_002": {"temperature": 23.1, "humidity": 55.8, "status": "inactive"},
    "device_003": {"temperature": 26.0, "humidity": 62.5, "status": "active", "battery_level": 85},
}

def receive_device_data(device_id: str) -> dict:
    """
    Simulates receiving a data packet from a specified IoT device.

    Args:
        device_id: The unique identifier of the device.

    Returns:
        A dictionary representing the data packet from the device.

    Raises:
        KeyError: If the device_id is not found in DEVICE_DATA.
    """
    if device_id in DEVICE_DATA:
        return DEVICE_DATA[device_id]
    else:
        raise KeyError(f"Data for device_id '{device_id}' not found.")

def validate_signature(data: str, signature: str) -> bool:
    """
    Validates the signature of the data.

    Args:
        data: The data string to validate.
        signature: The signature string to compare against.

    Returns:
        True if the signature is valid, False otherwise.
    """
    try:
        # Create a new SHA256 hash object
        hasher = hashlib.sha256()
        # Update the hash object with the data (encoded to bytes)
        hasher.update(data.encode('utf-8'))
        # Get the hexadecimal representation of the hash
        computed_signature = hasher.hexdigest()
        # Compare the computed signature with the provided signature
        return computed_signature == signature
    except Exception:
        # If any error occurs (e.g., during encoding or hashing), return False
        return False

# Setup code from the problem description
TRUSTED_DEVICE_SIGNATURES = {
    "device001": "89ebf76ae45bfcf6dd7f2aa3de8b20b3", # Example MD5-like signature
    "device002": "1dcfa479db7aae3d40b3984cdf202de6"  # Example MD5-like signature
}

# Simulated function to receive a data packet from the IoT device (as provided in setup)
def receive_data_packet(id_device: str):
    if id_device in TRUSTED_DEVICE_SIGNATURES:
        return {"temperature": 22.5, "humidity": 60}
    else:
        raise ConnectionError(f"Failed to receive packet from device {id_device}")

def process_packet_data(id_device: str, packet_signature: str, packet_data: dict) -> dict | None:
    """
    Processes a data packet by validating its source and cryptographic signature.

    Args:
        id_device: The identifier of the device sending the packet.
        packet_signature: The cryptographic signature accompanying the packet.
        packet_data: The data packet (dictionary) itself.

    Returns:
        The packet_data if the device is trusted and the signature is valid,
        otherwise None.
    """
    if id_device not in TRUSTED_DEVICE_SIGNATURES:
        print(f"Warning: Device ID '{id_device}' is not in the list of trusted devices.")
        return None

    try:
        # Serialize the dictionary to a canonical string format (sorted keys)
        # This ensures that the order of items in the dictionary doesn't affect the hash
        data_string = json.dumps(packet_data, sort_keys=True)
    except TypeError:
        print(f"Error: Could not serialize packet_data for device '{id_device}'. Malformed data?")
        return None

    if validate_signature(data_string, packet_signature):
        return packet_data
    else:
        print(f"Warning: Invalid signature for data from device '{id_device}'. Data integrity compromised.")
        return None

if __name__ == '__main__':
    # Example usage for receive_device_data:
    try:
        packet1 = receive_device_data("device_001")
        print(f"Received data from device_001: {packet1}")

        packet2 = receive_device_data("device_003")
        print(f"Received data from device_003: {packet2}")

        # This will raise a KeyError
        # packet3 = receive_device_data("device_004")
        # print(f"Received data from device_004: {packet3}")
    except KeyError as e:
        print(e)

    # Example usage for validate_signature:
    sample_data = "This is some sample data."
    # Simulate a correct signature (SHA256 hash of sample_data)
    # In a real scenario, the signature would be generated by the device using a secret key
    # or a more complex cryptographic method. For this example, we'll pre-compute it.
    correct_signature_generator = hashlib.sha256()
    correct_signature_generator.update(sample_data.encode('utf-8'))
    correct_signature = correct_signature_generator.hexdigest()

    incorrect_signature = "thisisawrongsignature"

    is_valid_correct = validate_signature(sample_data, correct_signature)
    print(f"Validation with correct signature: {is_valid_correct}") # Expected: True

    is_valid_incorrect = validate_signature(sample_data, incorrect_signature)
    print(f"Validation with incorrect signature: {is_valid_incorrect}") # Expected: False

    is_valid_tampered_data = validate_signature("This is some tampered data.", correct_signature)
    print(f"Validation with tampered data and original signature: {is_valid_tampered_data}") # Expected: False

    # Example usage for process_packet_data:
    print("\n--- Testing process_packet_data ---")
    sample_payload = {"temperature": 22.5, "humidity": 60, "location": "lab1", "value": 100}

    # Generate a correct SHA256 signature for the sample_payload
    # This signature needs to be SHA256 because validate_signature uses SHA256
    payload_string_for_signature = json.dumps(sample_payload, sort_keys=True)
    correct_payload_signature_generator = hashlib.sha256()
    correct_payload_signature_generator.update(payload_string_for_signature.encode('utf-8'))
    correct_payload_sha256_signature = correct_payload_signature_generator.hexdigest()

    # Case 1: Valid device ("device001" is in TRUSTED_DEVICE_SIGNATURES), valid SHA256 signature
    print("\nCase 1: Valid device, valid signature")
    processed_data_case1 = process_packet_data("device001", correct_payload_sha256_signature, sample_payload)
    if processed_data_case1:
        print(f"Successfully processed data for device001: {processed_data_case1}")
    else:
        print(f"Failed to process data for device001.")

    # Case 2: Valid device, but invalid signature
    print("\nCase 2: Valid device, invalid signature")
    invalid_sha256_signature = "thisisdefinitelynotthecorrectsha256signatureandiswrong"
    processed_data_case2 = process_packet_data("device001", invalid_sha256_signature, sample_payload)
    if processed_data_case2:
        print(f"Should not happen: Processed data for device001 with invalid sig: {processed_data_case2}")
    else:
        print(f"Correctly failed to process data for device001 due to invalid signature.")

    # Case 3: Unknown device ("device999" is not in TRUSTED_DEVICE_SIGNATURES)
    print("\nCase 3: Unknown device")
    processed_data_case3 = process_packet_data("device999", correct_payload_sha256_signature, sample_payload)
    if processed_data_case3:
        print(f"Should not happen: Processed data for unknown device999: {processed_data_case3}")
    else:
        print(f"Correctly failed to process data for unknown device999.")

    # Case 4: Valid device, signature is one from TRUSTED_DEVICE_SIGNATURES (MD5-like, so will fail SHA256 validation)
    print("\nCase 4: Valid device, but using MD5-like signature from TRUSTED_DEVICE_SIGNATURES with SHA256 validation")
    md5_like_sig_from_trusted = TRUSTED_DEVICE_SIGNATURES["device001"] # This is "89ebf76ae45bfcf6dd7f2aa3de8b20b3"
    processed_data_case4 = process_packet_data("device001", md5_like_sig_from_trusted, sample_payload)
    if processed_data_case4:
        print(f"Should not happen: Processed data for device001 with MD5-like sig: {processed_data_case4}")
    else:
        print(f"Correctly failed to process data for device001 with MD5-like signature (expected SHA256).")
