import hashlib # Required for cryptographic signature (conceptual)

TRUSTED_USER_PROFILES = {
    "user_abc": "4e99a098d57cbf9c6f67f176106769fb", # md5("user_abc_profile_data_secret")
    "user_xyz": "12e4b2f76650484030e4d447d0b5f723"  # md5("user_xyz_profile_data_secret")
}

def get_profile_from_service(user_id: str):
    """
    Simulates fetching a user profile from a remote service.
    In a real scenario, this would involve an HTTP request.
    """
    # Simulate profile data that would be fetched
    if user_id == "user_abc":
        return {"name": "Alice Alpha", "email": f"{user_id}@example.com", "data": "user_abc_profile_data"}
    elif user_id == "user_xyz":
        return {"name": "Bob Beta", "email": f"{user_id}@example.com", "data": "user_xyz_profile_data"}
    else:
        # Simulate a case where the user is not found or an error occurs
        raise ConnectionError(f"Could not fetch profile for user_id {user_id}")

def generate_signature(data_string: str, secret_key: str) -> str:
    """
    Generates a conceptual signature (e.g., HMAC-SHA256 or a simple hash for demo).
    In a real application, use a strong cryptographic library for HMAC.
    This is a simplified example using MD5 for demonstration.
    """
    # For demonstration, let's assume the signature is an MD5 hash of (data + secret)
    # In a real system, this would be more complex and secure, likely involving the actual profile data.
    # Here, we'll use a placeholder "secret" suffix for the hash.
    return hashlib.md5((data_string + "_secret").encode()).hexdigest()


def fetch_user_profile(user_id: str, signature: str):
    """
    Retrieves a user profile from a remote service and verifies it using a cryptographic signature.

    Args:
        user_id: The unique identifier of the user.
        signature: The cryptographic signature to verify against the fetched profile.

    Returns:
        The profile data if the signature is valid, otherwise None.
    """
    try:
        profile_data = get_profile_from_service(user_id)
    except ConnectionError:
        print(f"Error: Could not connect to service for user {user_id}.")
        return None

    if not profile_data:
        return None

    # For this example, let's assume the signature in TRUSTED_USER_PROFILES
    # is a pre-calculated signature of some representation of the user's profile data.
    # We'll simulate this by checking against the stored signature.
    # A more realistic scenario would involve hashing the received profile_data
    # (perhaps with a shared secret) and comparing it to the provided signature.

    # Conceptual verification:
    # The provided 'signature' argument should match the known good signature for this user_id.
    # In a real system, the 'signature' would be generated by the client/service
    # based on the profile data itself using a shared secret or public/private key pair.
    # Here, we are simplifying by checking if the provided signature matches the
    # one stored in TRUSTED_USER_PROFILES.

    # Let's refine the verification to be more illustrative.
    # Assume the signature provided is for the 'data' field within the profile.
    # And TRUSTED_USER_PROFILES stores the expected signature for that 'data' field.

    expected_signature_for_data = TRUSTED_USER_PROFILES.get(user_id)

    if not expected_signature_for_data:
        print(f"User ID {user_id} not found in trusted profiles for signature verification.")
        return None

    # Let's assume the 'signature' argument is what we *expect* for the profile's 'data' field.
    # And the `TRUSTED_USER_PROFILES` contains the *actual* correct signature for the `data` field.
    # This is a bit circular for a demo.
    # A better demo: the `signature` argument is provided by the *caller*,
    # and we verify it against a signature we *compute* from `profile_data["data"]`.

    # Let's re-think: The `signature` argument is what the *caller* provides.
    # `TRUSTED_USER_PROFILES` contains the *correct* signature for the user's *data*.
    # We need to check if the provided `signature` matches the one in `TRUSTED_USER_PROFILES`.

    if signature == expected_signature_for_data:
        # Signature matches the trusted one for this user ID.
        # We can now return the profile data (excluding the raw 'data' used for signature for simplicity).
        return {"name": profile_data["name"], "email": profile_data["email"]}
    else:
        print(f"Signature verification failed for user {user_id}.")
        return None


if __name__ == '__main__':
    # Example Usage

    # Scenario 1: Valid user and correct signature
    # To make this work, the signature passed to fetch_user_profile should be the one from TRUSTED_USER_PROFILES
    print("Scenario 1: Valid user, correct signature")
    profile1 = fetch_user_profile("user_abc", "4e99a098d57cbf9c6f67f176106769fb")
    print(f"Profile for user_abc: {profile1}\n")

    # Scenario 2: Valid user but incorrect signature
    print("Scenario 2: Valid user, incorrect signature")
    profile2 = fetch_user_profile("user_xyz", "incorrect_signature_value")
    print(f"Profile for user_xyz (with incorrect sig): {profile2}\n")

    # Scenario 3: User not in TRUSTED_USER_PROFILES (signature check will fail as no trusted sig exists)
    print("Scenario 3: User not in trusted list (for signature)")
    # get_profile_from_service might still return data if it existed there,
    # but fetch_user_profile would fail at signature check.
    # Let's use a user_id that get_profile_from_service doesn't know to also show ConnectionError
    profile3 = fetch_user_profile("user_unknown", "somesig")
    print(f"Profile for user_unknown: {profile3}\n")

    # Scenario 4: User known to service, but not in TRUSTED_USER_PROFILES for signature
    # Add a temporary user to get_profile_from_service for this test
    def get_profile_from_service_temp(user_id: str):
        if user_id == "user_def":
            return {"name": "David Delta", "email": f"{user_id}@example.com", "data": "user_def_profile_data"}
        return get_profile_from_service(user_id) # fallback to original

    original_get_profile = get_profile_from_service
    get_profile_from_service = get_profile_from_service_temp # monkey patch for test

    print("Scenario 4: User data fetchable, but no trusted signature")
    profile4 = fetch_user_profile("user_def", "any_signature_will_do_for_test")
    print(f"Profile for user_def: {profile4}\n")

    get_profile_from_service = original_get_profile # revert monkey patch
