def create_static_html():
    """
    Returns a basic HTML string with a welcome message.
    """
    html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
</head>
<body>
    <header>
        <h1>Welcome to Our Page!</h1>
    </header>
    <main>
        <p>This is a simple static HTML page generated by Python.</p>
    </main>
</body>
</html>
"""
    return html_content

if __name__ == '__main__':
    # Example usage:
    # To see the output, you could write this to a file and open it in a browser.
    # For example:
    # with open("welcome.html", "w") as f:
    #     f.write(create_static_html())
    # print("HTML page 'welcome.html' created.")
    print(create_static_html())
