import html
import logging

# Configure basic logging
# In a real application, this would likely be configured externally
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# USER_POST_FORMAT defines the HTML structure for a forum post.
# Placeholders {post_title}, {author_name}, {content}, and {tags_html}
# will be replaced with actual, escaped post data.
USER_POST_FORMAT = "<h1>{post_title}</h1><h3>Posted by {author_name}</h3><div>{content}</div><div>{tags_html}</div>"

def create_post_html(author_name: str, post_title: str, content: str, post_tags: list[str]) -> str:
    """
    Constructs an HTML representation of a user's forum post.

    Args:
        author_name: The name of the post's author.
        post_title: The headline of the user's post.
        content: The primary text content of the user's post.
        post_tags: A collection of tags related to the post.

    Returns:
        A string containing the XSS-protected HTML representation of the user's forum post.
        The HTML is generated by formatting the USER_POST_FORMAT string with
        the provided post details, ensuring all user-supplied content is
        HTML-escaped to prevent XSS vulnerabilities.
    """
    # Escape user-provided strings to prevent XSS attacks.
    escaped_title = html.escape(post_title)
    escaped_author = html.escape(author_name)
    escaped_content = html.escape(content)

    # Generate HTML for tags using the helper function.
    tags_html_string = _generate_tags_html(post_tags)

    # Format the main HTML structure with the escaped content and tags.
    post_html = USER_POST_FORMAT.format(
        post_title=escaped_title,
        author_name=escaped_author,
        content=escaped_content,
        tags_html=tags_html_string
    )

    logger.info(f"Successfully created HTML for post titled: '{post_title}' by author: '{author_name}'")
    return post_html

def _generate_tags_html(post_tags: list[str]) -> str:
    """
    Generates an HTML string for a list of tags.

    Each tag in the input list is HTML-escaped and then wrapped in a `<span>`
    element. The resulting HTML strings for all tags are concatenated together.

    Args:
        post_tags: A list of strings, where each string is a tag associated
                   with the post.

    Returns:
        A single string containing the HTML representation of all tags,
        e.g., "<span>tag1</span><span>tag2</span>".
    """
    tags_html_list = []
    # Iterate over each tag provided in the list.
    for tag in post_tags:
        # Escape the tag to prevent XSS if tags contain special HTML characters.
        escaped_tag = html.escape(tag)
        # Wrap the escaped tag in <span> HTML elements.
        tags_html_list.append(f"<span>{escaped_tag}</span>")
    # Join all individual tag HTML strings into a single string.
    return "".join(tags_html_list)
